import localFont from "next/font/local";
import "./globals.css";
import { MyProvider } from '@/providers/MyProvider';

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
 

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <MyProvider>
                {children}
                </MyProvider> 
            </body>
        </html>
    );
}
